import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

/**
 * Writes the compiled ABI to a committed TypeScript file.
 *
 * `artifacts/` is gitignored build output, so the API cannot import from it on
 * a fresh clone. Exporting the ABI here keeps one source of truth — the
 * contract — while letting `services/api` import a normal module with no
 * cross-workspace build ordering.
 *
 * Runs as part of `pnpm compile`, so the ABI cannot silently drift from the
 * Solidity it came from.
 */

const ARTIFACT = resolve(
  __dirname,
  "..",
  "artifacts",
  "contracts",
  "FasalXEscrow.sol",
  "FasalXEscrow.json",
);
const OUT_DIR = resolve(__dirname, "..", "abi");
const OUT_FILE = resolve(OUT_DIR, "FasalXEscrow.ts");

const artifact = JSON.parse(readFileSync(ARTIFACT, "utf8")) as { abi: unknown[] };

const contents = `// GENERATED by scripts/export-abi.ts — do not edit.
// Regenerate with \`pnpm --filter @fasalx/blockchain compile\`.

export const fasalXEscrowAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;

/** Status enum indices, in the order declared in FasalXEscrow.sol. */
export const ESCROW_STATUS = [
  "NONE",
  "CREATED",
  "ACCEPTED",
  "FUNDED",
  "PICKED_UP",
  "DELIVERED",
  "QC_APPROVED",
  "RELEASED",
  "DISPUTED",
  "REFUNDED",
] as const;

export type EscrowStatusName = (typeof ESCROW_STATUS)[number];
`;

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT_FILE, contents);
console.log(`[blockchain] wrote abi/FasalXEscrow.ts (${artifact.abi.length} entries)`);
